### ISSUE TITLE
Definição do tema

### ISSUE THREAD

**Issue by AnaCarolcs** [deeplearningunb/Detector-de-mascara#2]
Definição do tema e requisitos do sistema que será desenvolvido.

**Comment by Matheus73** [comment]
# Opções cotadas:
* Identificador de máscaras
* Identificador de óculos de segurança em profissionais de construção civil
* Identificador de Capacetes de motos para aplicação de multas

**Comment by AnaCarolcs** [comment]
Dado o contexto da pandemia, optamos pelo identificador de máscaras, por ser mais atual e aplicável.
