### ISSUE TITLE
Ajustar modelo para identificar faces

### ISSUE THREAD

**Issue by AnaCarolcs** [deeplearningunb/Detector-de-mascara#8]
Ajuste do modelo para identificar a face humana

**Comment by Matheus73** [comment]
Adicionado modelo pré-treinado para identificar rostos (disponivel no repositorio do opencv), e adicionado no script de dect_faces.py

**Comment by Matheus73** [comment]
Retirado o modelo por ser um modelo antigo que não foi treinado para utilizar imagens de pessoas com mascaras
